# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore DotNetCoreWebAPI/DotNetCoreWebAPI.csproj
      working-directory: DotNetCoreWebAPI
    - name: Build
      run: dotnet build DotNetCoreWebAPI/DotNetCoreWebAPI.csproj --no-restore
      working-directory: DotNetCoreWebAPI
    - name: Test
      run: dotnet test DotNetCoreWebAPI.Tests/DotNetCoreWebAPI.Tests.csproj --no-build --verbosity normal
      working-directory: DotNetCoreWebAPI

